const allRoles = {
  user: [
    'uploadDocuments',
    'viewNotarizationHistory',
    'createSession',
    'addUserToSession',
    'deleteUserOutOfSession',
    'joinSession',
    'getNotarizationFields',
    'getNotarizationServices',
    'approveSignatureByUser',
    'approveSignatureSessionByUser',
    'searchUserByEmail',
    'getSessionsByUserId',
    'getSessionBySessionId',
    'uploadSessionDocument',
    'sendSessionForNotarization',
    'getSessionStatus',
    'getDocument',
    'getWallet',
    'transferNFT',
    'purchaseDocument',
  ],
  admin: [
    'getUsers',
    'manageUsers',
    'uploadDocuments',
    'viewNotarizationHistory',
    'manageRoles',
    'manageNotarizationFields',
    'manageNotarizationServices',
    'getAllNotarizations',
    'getDocumentCount',
    'getUserCount',
    'getDocumentsByNotaryField',
    'getEmployeeCount',
    'getEmployeeList',
    'getNotarizationFields',
    'getNotarizationServices',
    'getSessions',
    'getSessionCount',
    'searchUserByEmail',
    'createSession',
    'addUserToSession',
    'deleteUserOutOfSession',
    'joinSession',
    'getPaymentTotal',
    'getPaymentTotalByService',
    'approveSignatureByUser',
    'approveSignatureBySecretary',
    'getPaymentTotalByNotarizationField',
    'getSessionStatus',
    'viewNotarizationHistoryByUserId',
    'getDocument',
    'getSessionsByStatus',
    'exportMetrics',
  ],
  notary: [
    'getDocumentsByRole',
    'forwardDocumentStatus',
    'getApproveHistory',
    'joinSession',
    'getSessionBySessionId',
    'getSessionStatus',
    'getSessionsByStatus',
    'forwardSessionStatus',
    'approveSignatureByNotary',
    'approveSignatureSessionNotary',
    'approveSignatureSessionByNotary',
    'notaryDashboard',
    'getDocument',
  ],
};

const roles = Object.keys(allRoles);
const roleRights = new Map(Object.entries(allRoles));

const getPermissionsByRoleName = (roleName) => {
  return roleRights.get(roleName);
};

module.exports = {
  roles,
  roleRights,
  getPermissionsByRoleName,
};
